/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vistas;

import hibernate.InsertarDatos;
import javax.swing.JOptionPane;

/**
 *
 * @author MIGUE
 */
public class RegistroProfesor extends javax.swing.JFrame {

    /**
     * Creates new form RegistroProfesor
     */
    public RegistroProfesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInsertarProfesor = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        textDni1 = new javax.swing.JTextField();
        textApellidos1 = new javax.swing.JTextField();
        textDomicilio1 = new javax.swing.JTextField();
        textTelefono1 = new javax.swing.JTextField();
        btnAceptarProfesor = new javax.swing.JButton();
        btnCancelarProfesor = new javax.swing.JButton();
        textNombre1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelInsertarProfesor.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro  profesor/a\n"));

        jLabel8.setText("Dni:");

        jLabel13.setText("Nombre:");

        jLabel14.setText("Apellidos:");

        jLabel15.setText("Domicilio:");

        jLabel16.setText("Telefono:");

        btnAceptarProfesor.setText("Aceptar");
        btnAceptarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarProfesorActionPerformed(evt);
            }
        });

        btnCancelarProfesor.setText("Cancelar");
        btnCancelarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarProfesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInsertarProfesorLayout = new javax.swing.GroupLayout(jPanelInsertarProfesor);
        jPanelInsertarProfesor.setLayout(jPanelInsertarProfesorLayout);
        jPanelInsertarProfesorLayout.setHorizontalGroup(
            jPanelInsertarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertarProfesorLayout.createSequentialGroup()
                .addGroup(jPanelInsertarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInsertarProfesorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelInsertarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInsertarProfesorLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(textDni1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)))
                    .addGroup(jPanelInsertarProfesorLayout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelInsertarProfesorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInsertarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInsertarProfesorLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertarProfesorLayout.createSequentialGroup()
                        .addGroup(jPanelInsertarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInsertarProfesorLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(textApellidos1))
                            .addGroup(jPanelInsertarProfesorLayout.createSequentialGroup()
                                .addGap(0, 13, Short.MAX_VALUE)
                                .addComponent(textTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanelInsertarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInsertarProfesorLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel15))
                            .addGroup(jPanelInsertarProfesorLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(textDomicilio1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelInsertarProfesorLayout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(btnCancelarProfesor)))
                        .addGap(149, 149, 149))
                    .addGroup(jPanelInsertarProfesorLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertarProfesorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAceptarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174))))
        );
        jPanelInsertarProfesorLayout.setVerticalGroup(
            jPanelInsertarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertarProfesorLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelInsertarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textDni1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanelInsertarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(14, 14, 14)
                .addGroup(jPanelInsertarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textApellidos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textDomicilio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanelInsertarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(btnAceptarProfesor))
                .addGap(18, 18, 18)
                .addGroup(jPanelInsertarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarProfesor))
                .addGap(131, 131, 131))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addComponent(textNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelInsertarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(textNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelInsertarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarProfesorActionPerformed
        // TODO add your handling code here:

        IngresarProfesor();
    }//GEN-LAST:event_btnAceptarProfesorActionPerformed

    private void btnCancelarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProfesorActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarProfesorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptarProfesor;
    private javax.swing.JButton btnCancelarProfesor;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanelInsertarProfesor;
    public javax.swing.JTextField textApellidos1;
    public javax.swing.JTextField textDni1;
    public javax.swing.JTextField textDomicilio1;
    public javax.swing.JTextField textNombre1;
    public javax.swing.JTextField textTelefono1;
    // End of variables declaration//GEN-END:variables

    private void IngresarProfesor(){
        
        boolean comprobacioncamposprofesor;
        
         String dni=textDni1.getText();
            String nombre=textNombre1.getText();
            String apellidos=textApellidos1.getText();
            String domicilio=textDomicilio1.getText();
            String telefono=textTelefono1.getText();
            
            if((dni.equals("") || nombre.equals("") || apellidos.equals("") || domicilio.equals("")) || telefono.equals(""))
            {
                comprobacioncamposprofesor=true;
            }
            
            else
            {
                comprobacioncamposprofesor=false;
            }
            
            if(!comprobacioncamposprofesor)
            {
                InsertarDatos id=new InsertarDatos();
                id.insertarProfesor(dni, nombre, apellidos, domicilio, telefono);
                JOptionPane.showMessageDialog(null, "Registro realizado correctamente");
                
                textDni1.setText("");
                textNombre1.setText("");
                textApellidos1.setText("");
                textDomicilio1.setText("");
                textTelefono1.setText("");
            }
            
            
            else if(comprobacioncamposprofesor)
            {
                JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");
            }
        
    }


}
