/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.controladorAlumno;
import controlador.controladorAsignatura;
import controlador.controladorAula;
import controlador.controladorImparte;
import controlador.controladorMatricula;
import controlador.controladorProfesor;
import hibernate.FacultadFactory;
import java.awt.BorderLayout;
import java.util.Iterator;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import jcode.hibernate.modelo.Asignatura1;
import jcode.hibernate.modelo.Aula1;
import jcode.hibernate.modelo.Profesor1;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 *
 * @author Silvia
 */
public class VistaRegistro extends javax.swing.JFrame 
{
    /**
     * Creates new form InsertarAlumnos
     */
    public VistaRegistro() 
    {
        initComponents();
        PanelFondo F=new PanelFondo();  //Creamos el objeto F de tipo PanelFondo
        getContentPane().add(F,BorderLayout.CENTER);
        
        
        jPanel4.setVisible(false);
        jPanelImparte.setVisible(false);
        jPanelInsertarALumnos.setVisible(false);
        jPanelInsertarProfesor.setVisible(false);
        jPanelInsertarAula.setVisible(false);
        setLocationRelativeTo(null);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanelImparte = new javax.swing.JPanel();
        btnAceptarImparte = new javax.swing.JButton();
        btnCancelarAsignatura = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProfesores = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAulas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableAsignaturas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanelInsertarProfesor = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        textDni1 = new javax.swing.JTextField();
        textNombre1 = new javax.swing.JTextField();
        textApellidos1 = new javax.swing.JTextField();
        textDomicilio1 = new javax.swing.JTextField();
        textTelefono1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnAceptarProfesor = new javax.swing.JButton();
        btnCancelarProfesor = new javax.swing.JButton();
        jPanelInsertarAula = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnAceptarInsertarAula = new javax.swing.JButton();
        btnCancelarAula = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        textNombreEdificio = new javax.swing.JTextField();
        textnAula = new javax.swing.JTextField();
        jPanelInsertarAsignatura = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        textTitulo = new javax.swing.JTextField();
        textNCredito = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnAceptarAsignatura = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanelInsertarALumnos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textDni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        textNota = new javax.swing.JTextField();
        textDomicilio = new javax.swing.JTextField();
        textTelefono = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelarAlumno = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableAsignatura1 = new javax.swing.JTable();
        btnMostrarAsignaturas = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        textApellido = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAlumno = new javax.swing.JMenu();
        jMenuRegistrarAlumno = new javax.swing.JMenuItem();
        jMenuVerAlumno = new javax.swing.JMenuItem();
        jMenuAsignatura = new javax.swing.JMenu();
        jMenuItemRegistrarAsignatura = new javax.swing.JMenuItem();
        jMenuItemMostrarAsignatura = new javax.swing.JMenuItem();
        jMenuProfesor = new javax.swing.JMenu();
        jMenuItemInsertarProfesor = new javax.swing.JMenuItem();
        jMenuItemVerProfesores = new javax.swing.JMenuItem();
        jMenuItemVerImparte = new javax.swing.JMenuItem();
        jMenuAula = new javax.swing.JMenu();
        jMenuItemInsertarAula = new javax.swing.JMenuItem();
        jMenuItemVerAulas = new javax.swing.JMenuItem();
        jMenuMatricula = new javax.swing.JMenu();
        jMenuItemMatricular = new javax.swing.JMenuItem();
        jMenuItemVerMatricula = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jLabel2.setText("jLabel2");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel4.setLayout(new java.awt.CardLayout());

        jPanelImparte.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar asignaturas"));

        btnAceptarImparte.setText("Aceptar");
        btnAceptarImparte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarImparteActionPerformed(evt);
            }
        });

        btnCancelarAsignatura.setText("Cancelar");
        btnCancelarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAsignaturaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Profesores"));

        jTableProfesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableProfesores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Aulas"));

        jTableAulas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableAulas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Asignaturas"));

        jTableAsignaturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTableAsignaturas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton1.setText("Mostrar profesor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Mostrar asignaturas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Mostrar aulas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelImparteLayout = new javax.swing.GroupLayout(jPanelImparte);
        jPanelImparte.setLayout(jPanelImparteLayout);
        jPanelImparteLayout.setHorizontalGroup(
            jPanelImparteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImparteLayout.createSequentialGroup()
                .addGroup(jPanelImparteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelImparteLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(btnAceptarImparte)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarAsignatura))
                    .addGroup(jPanelImparteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelImparteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanelImparteLayout.setVerticalGroup(
            jPanelImparteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImparteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanelImparteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(btnAceptarImparte)
                    .addComponent(btnCancelarAsignatura))
                .addGap(26, 26, 26))
        );

        jPanel4.add(jPanelImparte, "card2");

        jPanelInsertarProfesor.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar profesor"));

        jLabel8.setText("Dni:");

        jLabel13.setText("Nombre:");

        jLabel14.setText("Apellidos:");

        jLabel15.setText("Domicilio:");

        jLabel16.setText("Telefono:");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/admin.png"))); // NOI18N

        btnAceptarProfesor.setText("Aceptar");
        btnAceptarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarProfesorActionPerformed(evt);
            }
        });

        btnCancelarProfesor.setText("Cancelar");
        btnCancelarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarProfesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInsertarProfesorLayout = new javax.swing.GroupLayout(jPanelInsertarProfesor);
        jPanelInsertarProfesor.setLayout(jPanelInsertarProfesorLayout);
        jPanelInsertarProfesorLayout.setHorizontalGroup(
            jPanelInsertarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertarProfesorLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanelInsertarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addGap(44, 44, 44)
                .addGroup(jPanelInsertarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textDni1)
                    .addComponent(textNombre1)
                    .addComponent(textApellidos1)
                    .addComponent(textDomicilio1)
                    .addComponent(textTelefono1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(58, 58, 58))
            .addGroup(jPanelInsertarProfesorLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(btnAceptarProfesor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarProfesor)
                .addGap(101, 101, 101))
        );
        jPanelInsertarProfesorLayout.setVerticalGroup(
            jPanelInsertarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertarProfesorLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanelInsertarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanelInsertarProfesorLayout.createSequentialGroup()
                        .addGroup(jPanelInsertarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textDni1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInsertarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textNombre1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInsertarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textApellidos1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInsertarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(textDomicilio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInsertarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(textTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(jPanelInsertarProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAceptarProfesor)
                            .addComponent(btnCancelarProfesor))))
                .addGap(50, 50, 50))
        );

        jPanel4.add(jPanelInsertarProfesor, "card4");

        jPanelInsertarAula.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar aula"));

        jLabel18.setText("Nombre edificio:");

        jLabel19.setText("Nº aula:");

        btnAceptarInsertarAula.setText("Aceptar");
        btnAceptarInsertarAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarInsertarAulaActionPerformed(evt);
            }
        });

        btnCancelarAula.setText("Cancelar");
        btnCancelarAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAulaActionPerformed(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aula.png"))); // NOI18N

        javax.swing.GroupLayout jPanelInsertarAulaLayout = new javax.swing.GroupLayout(jPanelInsertarAula);
        jPanelInsertarAula.setLayout(jPanelInsertarAulaLayout);
        jPanelInsertarAulaLayout.setHorizontalGroup(
            jPanelInsertarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertarAulaLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(btnAceptarInsertarAula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarAula)
                .addGap(106, 106, 106))
            .addGroup(jPanelInsertarAulaLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanelInsertarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(44, 44, 44)
                .addGroup(jPanelInsertarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInsertarAulaLayout.createSequentialGroup()
                        .addComponent(textNombreEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 368, Short.MAX_VALUE))
                    .addGroup(jPanelInsertarAulaLayout.createSequentialGroup()
                        .addComponent(textnAula, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addGap(62, 62, 62))))
        );
        jPanelInsertarAulaLayout.setVerticalGroup(
            jPanelInsertarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertarAulaLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanelInsertarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(textNombreEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelInsertarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInsertarAulaLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanelInsertarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textnAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(104, 104, 104)
                        .addGroup(jPanelInsertarAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAceptarInsertarAula)
                            .addComponent(btnCancelarAula)))
                    .addGroup(jPanelInsertarAulaLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel20)))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jPanel4.add(jPanelInsertarAula, "card5");

        jLabel9.setText("Titulo:");

        jLabel10.setText("Nº créditos:");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Book.png"))); // NOI18N

        btnAceptarAsignatura.setText("Aceptar");

        jButton6.setText("Cancelar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInsertarAsignaturaLayout = new javax.swing.GroupLayout(jPanelInsertarAsignatura);
        jPanelInsertarAsignatura.setLayout(jPanelInsertarAsignaturaLayout);
        jPanelInsertarAsignaturaLayout.setHorizontalGroup(
            jPanelInsertarAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertarAsignaturaLayout.createSequentialGroup()
                .addGroup(jPanelInsertarAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInsertarAsignaturaLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanelInsertarAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(37, 37, 37)
                        .addGroup(jPanelInsertarAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(textNCredito)))
                    .addGroup(jPanelInsertarAsignaturaLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(btnAceptarAsignatura)))
                .addGap(91, 91, 91)
                .addGroup(jPanelInsertarAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertarAsignaturaLayout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(35, 35, 35)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanelInsertarAsignaturaLayout.setVerticalGroup(
            jPanelInsertarAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertarAsignaturaLayout.createSequentialGroup()
                .addGroup(jPanelInsertarAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelInsertarAsignaturaLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jPanelInsertarAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(textTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelInsertarAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(textNCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelInsertarAsignaturaLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(jPanelInsertarAsignaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarAsignatura)
                    .addComponent(jButton6))
                .addGap(90, 90, 90))
        );

        jPanel4.add(jPanelInsertarAsignatura, "card6");

        jPanelInsertarALumnos.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar alumnos"));

        jLabel1.setText("DNI:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellidos:");

        jLabel5.setText("Domicilio:");

        jLabel6.setText("Telefono:");

        jLabel7.setText("Acceso:");

        textNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreActionPerformed(evt);
            }
        });

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelarAlumno.setText("Cancelar");
        btnCancelarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAlumnoActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selectividad", "Acceso mayores 25 años" }));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuarios.png"))); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Asignaturas"));

        jTableAsignatura1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTableAsignatura1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMostrarAsignaturas.setText("Mostrar asignaturas");
        btnMostrarAsignaturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarAsignaturasActionPerformed(evt);
            }
        });

        jLabel21.setText("Nota:");

        javax.swing.GroupLayout jPanelInsertarALumnosLayout = new javax.swing.GroupLayout(jPanelInsertarALumnos);
        jPanelInsertarALumnos.setLayout(jPanelInsertarALumnosLayout);
        jPanelInsertarALumnosLayout.setHorizontalGroup(
            jPanelInsertarALumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertarALumnosLayout.createSequentialGroup()
                .addGroup(jPanelInsertarALumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelInsertarALumnosLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanelInsertarALumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInsertarALumnosLayout.createSequentialGroup()
                                .addGroup(jPanelInsertarALumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelInsertarALumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanelInsertarALumnosLayout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(textDni, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelInsertarALumnosLayout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanelInsertarALumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(jPanelInsertarALumnosLayout.createSequentialGroup()
                                .addGroup(jPanelInsertarALumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanelInsertarALumnosLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel21)))
                                .addGap(0, 17, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInsertarALumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textNota, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel12)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelInsertarALumnosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanelInsertarALumnosLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnMostrarAsignaturas)
                .addGap(130, 130, 130)
                .addComponent(btnAceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarAlumno)
                .addGap(65, 65, 65))
        );
        jPanelInsertarALumnosLayout.setVerticalGroup(
            jPanelInsertarALumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertarALumnosLayout.createSequentialGroup()
                .addGroup(jPanelInsertarALumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInsertarALumnosLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanelInsertarALumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(textDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInsertarALumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(textApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanelInsertarALumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInsertarALumnosLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanelInsertarALumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelInsertarALumnosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(textDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelInsertarALumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(textNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelInsertarALumnosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelInsertarALumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarAsignaturas)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelarAlumno))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel4.add(jPanelInsertarALumnos, "card2");

        jMenuAlumno.setText("Alumnos");
        jMenuAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAlumnoActionPerformed(evt);
            }
        });

        jMenuRegistrarAlumno.setText("Registrar alumnos");
        jMenuRegistrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegistrarAlumnoActionPerformed(evt);
            }
        });
        jMenuAlumno.add(jMenuRegistrarAlumno);

        jMenuVerAlumno.setText("Ver todos los alumnos");
        jMenuVerAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVerAlumnoActionPerformed(evt);
            }
        });
        jMenuAlumno.add(jMenuVerAlumno);

        jMenuBar1.add(jMenuAlumno);

        jMenuAsignatura.setText("Asignatura");
        jMenuAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAsignaturaActionPerformed(evt);
            }
        });

        jMenuItemRegistrarAsignatura.setText("Registrar asignatura");
        jMenuItemRegistrarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegistrarAsignaturaActionPerformed(evt);
            }
        });
        jMenuAsignatura.add(jMenuItemRegistrarAsignatura);

        jMenuItemMostrarAsignatura.setText("Ver todas las asignaturas");
        jMenuItemMostrarAsignatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMostrarAsignaturaActionPerformed(evt);
            }
        });
        jMenuAsignatura.add(jMenuItemMostrarAsignatura);

        jMenuBar1.add(jMenuAsignatura);

        jMenuProfesor.setText("Profesor");

        jMenuItemInsertarProfesor.setText("Insertar profesor");
        jMenuItemInsertarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInsertarProfesorActionPerformed(evt);
            }
        });
        jMenuProfesor.add(jMenuItemInsertarProfesor);

        jMenuItemVerProfesores.setText("Ver todos los profesores");
        jMenuItemVerProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerProfesoresActionPerformed(evt);
            }
        });
        jMenuProfesor.add(jMenuItemVerProfesores);

        jMenuItemVerImparte.setText("Asignar asignatura y aula");
        jMenuItemVerImparte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerImparteActionPerformed(evt);
            }
        });
        jMenuProfesor.add(jMenuItemVerImparte);

        jMenuBar1.add(jMenuProfesor);

        jMenuAula.setText("Aula");

        jMenuItemInsertarAula.setText("Registrar aula");
        jMenuItemInsertarAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInsertarAulaActionPerformed(evt);
            }
        });
        jMenuAula.add(jMenuItemInsertarAula);

        jMenuItemVerAulas.setText("Ver todas las aulas");
        jMenuItemVerAulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerAulasActionPerformed(evt);
            }
        });
        jMenuAula.add(jMenuItemVerAulas);

        jMenuBar1.add(jMenuAula);

        jMenuMatricula.setText("Matricula");

        jMenuItemMatricular.setText("Matricular");
        jMenuItemMatricular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMatricularActionPerformed(evt);
            }
        });
        jMenuMatricula.add(jMenuItemMatricular);

        jMenuItemVerMatricula.setText("Ver todas las matriculas");
        jMenuItemVerMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVerMatriculaActionPerformed(evt);
            }
        });
        jMenuMatricula.add(jMenuItemVerMatricula);

        jMenuBar1.add(jMenuMatricula);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuAlumnoActionPerformed

    private void jMenuRegistrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegistrarAlumnoActionPerformed
        // TODO add your handling code here:
        jPanel4.setVisible(true);
        jPanelImparte.setVisible(false);
        jPanelInsertarALumnos.setVisible(true);
        jPanelInsertarProfesor.setVisible(false);
        
        tablaAlumnos ta=new tablaAlumnos();
//        tablaMatricula tm=new tablaMatricula();
        tablaAsignaturas tas=new tablaAsignaturas();
        new controladorAlumno(this, ta).iniciar();
    }//GEN-LAST:event_jMenuRegistrarAlumnoActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void textNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreActionPerformed

    private void jMenuAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAsignaturaActionPerformed
        // TODO add your handling code here:
        jPanel4.setVisible(true);
    }//GEN-LAST:event_jMenuAsignaturaActionPerformed

    private void jMenuItemRegistrarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarAsignaturaActionPerformed
        // TODO add your handling code here:
        jPanel4.setVisible(true);
        jPanelImparte.setVisible(false);
        jPanelInsertarALumnos.setVisible(false);
        jPanelInsertarProfesor.setVisible(false);
        jPanelInsertarAsignatura.setVisible(true);
        
        tablaAsignaturas tas=new tablaAsignaturas();
        new controladorAsignatura(this, tas).iniciar();
    }//GEN-LAST:event_jMenuItemRegistrarAsignaturaActionPerformed

    private void btnAceptarImparteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarImparteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarImparteActionPerformed

    private void jMenuItemInsertarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInsertarProfesorActionPerformed
        // TODO add your handling code here:
        tablaProfesor tp=new tablaProfesor();
        
        jPanel4.setVisible(true);
        jPanelInsertarALumnos.setVisible(false);
        jPanelImparte.setVisible(false);
        jPanelInsertarAula.setVisible(false);
        jPanelInsertarProfesor.setVisible(true);
                
        new controladorProfesor(this, tp).iniciar();
    }//GEN-LAST:event_jMenuItemInsertarProfesorActionPerformed

    private void btnAceptarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarProfesorActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnAceptarProfesorActionPerformed

    private void jMenuItemInsertarAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInsertarAulaActionPerformed
        // TODO add your handling code here:
        
        jPanel4.setVisible(true);
        jPanelInsertarALumnos.setVisible(false);
        jPanelImparte.setVisible(false);
        jPanelInsertarProfesor.setVisible(false);
        jPanelInsertarAula.setVisible(true);
        
        tablaAulas tau=new tablaAulas();
        new controladorAula(this, tau).iniciar();
    }//GEN-LAST:event_jMenuItemInsertarAulaActionPerformed

    private void btnAceptarInsertarAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarInsertarAulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarInsertarAulaActionPerformed

    private void jMenuVerAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVerAlumnoActionPerformed
        // TODO add your handling code here:
        tablaAlumnos ta=new tablaAlumnos();
//        tablaMatricula tm=new tablaMatricula();
        tablaAsignaturas tas=new tablaAsignaturas();
        
        jPanel4.setVisible(false);
        jPanelInsertarALumnos.setVisible(false);
        jPanelImparte.setVisible(false);
        jPanelInsertarAula.setVisible(false);
        jPanelInsertarProfesor.setVisible(false);
                
        new controladorAlumno(this, ta).iniciar();
        ta.setVisible(true);
    }//GEN-LAST:event_jMenuVerAlumnoActionPerformed

    private void btnCancelarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAlumnoActionPerformed
        // TODO add your handling code here:
       jPanel4.setVisible(false);
       jPanelInsertarALumnos.setVisible(false);
    }//GEN-LAST:event_btnCancelarAlumnoActionPerformed

    private void btnCancelarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAsignaturaActionPerformed
        // TODO add your handling code here:
        jPanel4.setVisible(false);
        jPanelImparte.setVisible(false);
    }//GEN-LAST:event_btnCancelarAsignaturaActionPerformed

    private void btnCancelarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProfesorActionPerformed
        // TODO add your handling code here:
        jPanel4.setVisible(false);
        jPanelInsertarProfesor.setVisible(false);
    }//GEN-LAST:event_btnCancelarProfesorActionPerformed

    private void btnCancelarAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAulaActionPerformed
        // TODO add your handling code here:
        jPanel4.setVisible(false);
        jPanelInsertarAula.setVisible(false);
    }//GEN-LAST:event_btnCancelarAulaActionPerformed

    private void jMenuItemMatricularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMatricularActionPerformed
        // TODO add your handling code here:
        VistaMatricular mat=new VistaMatricular();
        VerMatriculas vm=new VerMatriculas();
        
        jPanel4.setVisible(false);
        jPanelInsertarALumnos.setVisible(false);
        jPanelImparte.setVisible(false);
        jPanelInsertarAula.setVisible(false);
        jPanelInsertarProfesor.setVisible(false);
         
        new controladorMatricula(this, vm).iniciar();
        mat.setVisible(true);
    }//GEN-LAST:event_jMenuItemMatricularActionPerformed

    private void jMenuItemMostrarAsignaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMostrarAsignaturaActionPerformed
        // TODO add your handling code here:
        tablaAsignaturas tas=new tablaAsignaturas();
        
        jPanel4.setVisible(false);
        jPanelInsertarALumnos.setVisible(false);
        jPanelImparte.setVisible(false);
        jPanelInsertarAula.setVisible(false);
        jPanelInsertarProfesor.setVisible(false);
                
        new controladorAsignatura(this, tas).iniciar();
        tas.setVisible(true);
    }//GEN-LAST:event_jMenuItemMostrarAsignaturaActionPerformed

    private void jMenuItemVerProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerProfesoresActionPerformed
        // TODO add your handling code here:
        tablaProfesor tp=new tablaProfesor();
        
        jPanel4.setVisible(false);
        jPanelInsertarALumnos.setVisible(false);
        jPanelImparte.setVisible(false);
        jPanelInsertarAula.setVisible(false);
        jPanelInsertarProfesor.setVisible(false);
                
        new controladorProfesor(this, tp).iniciar();
        tp.setVisible(true);
    }//GEN-LAST:event_jMenuItemVerProfesoresActionPerformed

    private void jMenuItemVerAulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerAulasActionPerformed
        // TODO add your handling code here:
        tablaAulas tau=new tablaAulas();
        
        jPanel4.setVisible(false);
        jPanelInsertarALumnos.setVisible(false);
        jPanelImparte.setVisible(false);
        jPanelInsertarAula.setVisible(false);
        jPanelInsertarProfesor.setVisible(false);
                
        new controladorAula(this, tau).iniciar();
        tau.setVisible(true);
    }//GEN-LAST:event_jMenuItemVerAulasActionPerformed

    private void jMenuItemVerMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerMatriculaActionPerformed
        // TODO add your handling code here:
        VerMatriculas vm=new VerMatriculas();
        
        jPanel4.setVisible(false);
        jPanelInsertarALumnos.setVisible(false);
        jPanelImparte.setVisible(false);
        jPanelInsertarAula.setVisible(false);
        jPanelInsertarProfesor.setVisible(false);
                
        new controladorMatricula(this, vm).iniciar();
        vm.setVisible(true);
    }//GEN-LAST:event_jMenuItemVerMatriculaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mostrarProfesor();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        mostrarAsignaturas();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        mostrarAulas();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItemVerImparteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerImparteActionPerformed
        // TODO add your handling code here:
        jPanel4.setVisible(true);
        jPanelImparte.setVisible(true);
        jPanelInsertarALumnos.setVisible(false);
        jPanelInsertarProfesor.setVisible(false);
        jPanelInsertarAsignatura.setVisible(false);
        
        tablaAsignaturas tas=new tablaAsignaturas();
        new controladorImparte(this).iniciar();
    }//GEN-LAST:event_jMenuItemVerImparteActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jPanel4.setVisible(false);
        jPanelInsertarAsignatura.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnMostrarAsignaturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarAsignaturasActionPerformed
        // TODO add your handling code here:
        mostrarAsignaturas1();
    }//GEN-LAST:event_btnMostrarAsignaturasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistro().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptar;
    public javax.swing.JButton btnAceptarAsignatura;
    public javax.swing.JButton btnAceptarImparte;
    public javax.swing.JButton btnAceptarInsertarAula;
    public javax.swing.JButton btnAceptarProfesor;
    private javax.swing.JButton btnCancelarAlumno;
    private javax.swing.JButton btnCancelarAsignatura;
    private javax.swing.JButton btnCancelarAula;
    private javax.swing.JButton btnCancelarProfesor;
    private javax.swing.JButton btnMostrarAsignaturas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    public javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenuAlumno;
    private javax.swing.JMenu jMenuAsignatura;
    private javax.swing.JMenu jMenuAula;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemInsertarAula;
    private javax.swing.JMenuItem jMenuItemInsertarProfesor;
    private javax.swing.JMenuItem jMenuItemMatricular;
    private javax.swing.JMenuItem jMenuItemMostrarAsignatura;
    private javax.swing.JMenuItem jMenuItemRegistrarAsignatura;
    private javax.swing.JMenuItem jMenuItemVerAulas;
    private javax.swing.JMenuItem jMenuItemVerImparte;
    private javax.swing.JMenuItem jMenuItemVerMatricula;
    private javax.swing.JMenuItem jMenuItemVerProfesores;
    private javax.swing.JMenu jMenuMatricula;
    private javax.swing.JMenu jMenuProfesor;
    private javax.swing.JMenuItem jMenuRegistrarAlumno;
    private javax.swing.JMenuItem jMenuVerAlumno;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelImparte;
    private javax.swing.JPanel jPanelInsertarALumnos;
    private javax.swing.JPanel jPanelInsertarAsignatura;
    private javax.swing.JPanel jPanelInsertarAula;
    private javax.swing.JPanel jPanelInsertarProfesor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTable jTableAsignatura1;
    public javax.swing.JTable jTableAsignaturas;
    public javax.swing.JTable jTableAulas;
    public javax.swing.JTable jTableProfesores;
    public javax.swing.JTextField textApellido;
    public javax.swing.JTextField textApellidos1;
    public javax.swing.JTextField textDni;
    public javax.swing.JTextField textDni1;
    public javax.swing.JTextField textDomicilio;
    public javax.swing.JTextField textDomicilio1;
    public javax.swing.JTextField textNCredito;
    public javax.swing.JTextField textNombre;
    public javax.swing.JTextField textNombre1;
    public javax.swing.JTextField textNombreEdificio;
    public javax.swing.JTextField textNota;
    public javax.swing.JTextField textTelefono;
    public javax.swing.JTextField textTelefono1;
    public javax.swing.JTextField textTitulo;
    public javax.swing.JTextField textnAula;
    // End of variables declaration//GEN-END:variables


    private void mostrarProfesor()  
    {
        
        String consulta="from Profesor1";
        Session session= FacultadFactory.getSessionFactory().openSession();
        Query query=session.createQuery(consulta);
        List results=query.list();
        Iterator iterator=results.iterator();
                               
        DefaultTableModel m= new DefaultTableModel();
        m.addColumn("Id Profesor");
        m.addColumn("DNI");
        m.addColumn("Nombre");
        m.addColumn("Apellido");
        m.addColumn("Domicilio");
        m.addColumn("Telefono");
        m.addColumn("Id Supervisor");
                        
         while(iterator.hasNext())
         {
              Profesor1 profesor2=(Profesor1)iterator.next();
              
              Object[] datos=new Object[7];
              
              datos[0]=profesor2.getIdProfesor();
              datos[1]=profesor2.getDni();
              datos[2]=profesor2.getNombre();
              datos[3]=profesor2.getApellidos();
              datos[4]=profesor2.getDomicilio();
              datos[5]=profesor2.getTelefono();
              datos[6]=profesor2.getIdSupervisor();
              m.addRow(datos);
         }
                        
         jTableProfesores.setModel(m);
         session.close();
    
    }

    private void mostrarAsignaturas()
    {
        
        String consulta="from Asignatura1";
        Session session= FacultadFactory.getSessionFactory().openSession();
        Query query=session.createQuery(consulta);
        List results=query.list();
        Iterator iterator=results.iterator();
                               
        DefaultTableModel m= new DefaultTableModel();
        m.addColumn("Id Asignatura");
        m.addColumn("Titulo");
        m.addColumn("Nº créditos");
                        
         while(iterator.hasNext())
         {
              Asignatura1 asignatura2=(Asignatura1)iterator.next();
              
              Object[] datos=new Object[3];
              
              datos[0]=asignatura2.getIdAsignatura();
              datos[1]=asignatura2.getTitulo();
              datos[2]=asignatura2.getNcreditos();
              m.addRow(datos);
         }
                        
         jTableAsignaturas.setModel(m);
         session.close();
    
    }

    private void mostrarAulas() 
    {
       String consulta="from Aula1";
        Session session= FacultadFactory.getSessionFactory().openSession();
        Query query=session.createQuery(consulta);
        List results=query.list();
        Iterator iterator=results.iterator();
                               
        DefaultTableModel m= new DefaultTableModel();
        m.addColumn("Id Aula");
        m.addColumn("Nombre edificio");
        m.addColumn("Nº aula");
                        
         while(iterator.hasNext())
         {
              Aula1 aula2=(Aula1)iterator.next();
              
              Object[] datos=new Object[3];
              
              datos[0]=aula2.getIdAula();
              datos[1]=aula2.getNombreEdificio();
              datos[2]=aula2.getNaula();
              m.addRow(datos);
         }
                        
         jTableAulas.setModel(m);
         session.close();
    }

    private void btnCancelar() {
       this.dispose();
    }
    
    
     private void mostrarAsignaturas1()
    {
        
        String consulta="from Asignatura1";
        Session session= FacultadFactory.getSessionFactory().openSession();
        Query query=session.createQuery(consulta);
        List results=query.list();
        Iterator iterator=results.iterator();
                               
        DefaultTableModel m= new DefaultTableModel();
        m.addColumn("Id Asignatura");
        m.addColumn("Titulo");
        m.addColumn("Nº créditos");
                        
         while(iterator.hasNext())
         {
              Asignatura1 asignatura2=(Asignatura1)iterator.next();
              
              Object[] datos=new Object[3];
              
              datos[0]=asignatura2.getIdAsignatura();
              datos[1]=asignatura2.getTitulo();
              datos[2]=asignatura2.getNcreditos();
              m.addRow(datos);
         }
                        
         jTableAsignatura1.setModel(m);
         session.close();
    
    }
}
