package jcode.hibernate.modelo;
// Generated 20-nov-2013 12:23:54 by Hibernate Tools 3.2.1.GA



/**
 * Asignatura1 generated by hbm2java
 */
public class Asignatura1  implements java.io.Serializable {


     private Integer idAsignatura;
     private String titulo;
     private String ncreditos;

    public Asignatura1() {
    }

    public Asignatura1(String titulo, String ncreditos) {
       this.titulo = titulo;
       this.ncreditos = ncreditos;
    }
   
    public Integer getIdAsignatura() {
        return this.idAsignatura;
    }
    
    public void setIdAsignatura(Integer idAsignatura) {
        this.idAsignatura = idAsignatura;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getNcreditos() {
        return this.ncreditos;
    }
    
    public void setNcreditos(String ncreditos) {
        this.ncreditos = ncreditos;
    }




}


