package jcode.hibernate.modelo;
// Generated 20-nov-2013 12:23:54 by Hibernate Tools 3.2.1.GA


/**
 * Aula1 generated by hbm2java
 */
public class Aula1  implements java.io.Serializable {


     private Integer idAula;
     private String nombreEdificio;
     private String naula;

    public Aula1() {
    }

    public Aula1(String nombreEdificio, String naula) {
       this.nombreEdificio = nombreEdificio;
       this.naula = naula;
    }
   
    public Integer getIdAula() {
        return this.idAula;
    }
    
    public void setIdAula(Integer idAula) {
        this.idAula = idAula;
    }
    public String getNombreEdificio() {
        return this.nombreEdificio;
    }
    
    public void setNombreEdificio(String nombreEdificio) {
        this.nombreEdificio = nombreEdificio;
    }
    public String getNaula() {
        return this.naula;
    }
    
    public void setNaula(String naula) {
        this.naula = naula;
    }




}


