package jcode.hibernate.modelo;
// Generated 20-nov-2013 12:23:54 by Hibernate Tools 3.2.1.GA


/**
 * Imparte generated by hbm2java
 */
public class Imparte  implements java.io.Serializable {


     private Long idImparte;
     private String tituloAsignatura;
     private String nombreProfesor;
     private Integer naula;

    public Imparte() {
    }

    public Imparte(String tituloAsignatura, String nombreProfesor, Integer naula) {
       this.tituloAsignatura = tituloAsignatura;
       this.nombreProfesor = nombreProfesor;
       this.naula = naula;
    }
   
    public Long getIdImparte() {
        return this.idImparte;
    }
    
    public void setIdImparte(Long idImparte) {
        this.idImparte = idImparte;
    }
    public String getTituloAsignatura() {
        return this.tituloAsignatura;
    }
    
    public void setTituloAsignatura(String tituloAsignatura) {
        this.tituloAsignatura = tituloAsignatura;
    }
    public String getNombreProfesor() {
        return this.nombreProfesor;
    }
    
    public void setNombreProfesor(String nombreProfesor) {
        this.nombreProfesor = nombreProfesor;
    }
    public Integer getNaula() {
        return this.naula;
    }
    
    public void setNaula(Integer naula) {
        this.naula = naula;
    }




}


