package jcode.hibernate.modelo;
// Generated 20-nov-2013 12:23:54 by Hibernate Tools 3.2.1.GA


/**
 * Matricula1 generated by hbm2java
 */
public class Matricula1  implements java.io.Serializable {


     private MatriculaId id=new MatriculaId();
     private String nota;

    public Matricula1() {
    }

    public Matricula1(MatriculaId id, String nota) {
       this.id = id;
       this.nota = nota;
    }
   
    public MatriculaId getId() {
        return this.id;
    }
    
    public void setId(MatriculaId id) {
        this.id = id;
    }
    public String getNota() {
        return this.nota;
    }
    
    public void setNota(String nota) {
        this.nota = nota;
    }
}


