package jcode.hibernate.modelo;
// Generated 20-nov-2013 12:23:54 by Hibernate Tools 3.2.1.GA


/**
 * MatriculaId generated by hbm2java
 */
public class MatriculaId  implements java.io.Serializable {


     private int idMatricula;
     private String idAlumno;
     private int idAsignatura;

    public MatriculaId() {
    }

    public MatriculaId(int idMatricula, String idAlumno, int idAsignatura) {
       this.idMatricula = idMatricula;
       this.idAlumno = idAlumno;
       this.idAsignatura = idAsignatura;
    }
   
    public int getIdMatricula() {
        return this.idMatricula;
    }
    
    public void setIdMatricula(int idMatricula) {
        this.idMatricula = idMatricula;
    }
    public String getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(String idAlumno) {
        this.idAlumno = idAlumno;
    }
    public int getIdAsignatura() {
        return this.idAsignatura;
    }
    
    public void setIdAsignatura(int idAsignatura) {
        this.idAsignatura = idAsignatura;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MatriculaId) ) return false;
		 MatriculaId castOther = ( MatriculaId ) other; 
         
		 return (this.getIdMatricula()==castOther.getIdMatricula())
 && (this.getIdAlumno()==castOther.getIdAlumno())
 && (this.getIdAsignatura()==castOther.getIdAsignatura());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdMatricula();
//         result = 37 * result + this.getIdAlumno();
         result = 37 * result + this.getIdAsignatura();
         return result;
   }   


}


